name: Test

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - '**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**/*.swift'

jobs:
  swift-test:
    strategy:
      fail-fast: true
      matrix:
        operating-system: ["ubuntu-20.04", "ubuntu-22.04"]
        swift-version: ["5.6.3", "5.7.3", "5.8.1"]
        exclude:
          - swift-version: "5.6.3"
            operating-system: "ubuntu-22.04"
    uses: shizukusoft/workflows/.github/workflows/swift-test.yml@main
    with:
      runs-on: ${{ matrix.operating-system }}
      swift-version: ${{ matrix.swift-version }}
