name: Test

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - '**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**/*.swift'

jobs:
  swift-test:
    strategy:
      fail-fast: true
      matrix:
        operating-system: ["ubuntu-20.04", "ubuntu-22.04"]
        swift-version: ["5.6.3", "5.7.3", "5.8.1"]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v3
      - uses: sinoru/actions-setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Build
        uses: sinoru/actions-swift@v1
        with:
          swift-image-tag: null
          args: build --enable-test-discovery
        env:
          SWIFT_VERSION: ${{ matrix.swift-version }}
      - name: Run tests
        uses: sinoru/actions-swift@v1
        with:
          swift-image-tag: null
          args: test --enable-test-discovery
        env:
          SWIFT_VERSION: ${{ matrix.swift-version }}
  xcode-test:
    strategy:
      fail-fast: true
      matrix:
        xcode-version: ["13.4.1", "14.3.1"]
        xcode-destination: [
          "platform=OS X,arch=x86_64",
          "platform=OS X,arch=x86_64,variant=Mac Catalyst",
          "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest",
          "platform=tvOS Simulator,name=Apple TV,OS=latest",
          "platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm,OS=latest",
        ]
        include:
          - xcode-version: "13.4.1"
            operating-system: "macos-12"
          - xcode-version: "14.3.1"
            operating-system: "macos-13"
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v3
      - uses: sinoru/actions-setup-xcode@v2
        with:
          xcode-version: ${{ matrix.xcode-version }}
          apple-id: ${{ secrets.APPLE_ID }}
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
      - name: Resolve Package Dependencies
        run: xcodebuild -resolvePackageDependencies
      - name: Analyze
        run: xcodebuild -scheme swift-snowflake-Package -destination '${{ matrix.xcode-destination }}' analyze
      - name: Test
        run: xcodebuild -scheme swift-snowflake-Package -destination '${{ matrix.xcode-destination }}' test
